"""Rendering helpers for generated files: `generated: true` pages, the
`<!-- tess:gen:<id>:start/end -->` marker grammar (spec 9.2), relative links
and paging of long lists into brain/index/*.md (spec 10.7).
"""
from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Dict, List, Tuple

from .caps import PAGE_SIZE
from .textutil import clip

GEN_NOTE = "<!-- generated by scripts/brain/tessbrain.py index; edits here are overwritten -->"


class Item:
    """One list line: `- <pre>[<text>](<link to target>)<post>`."""

    __slots__ = ("pre", "text", "target", "post")

    def __init__(self, text: str, target: Path, pre: str = "", post: str = ""):
        self.pre, self.text, self.target, self.post = pre, text, Path(target), post

    def render(self, from_dir: Path) -> str:
        return "- %s[%s](%s)%s" % (self.pre, md_escape(self.text), link(from_dir, self.target), self.post)


def md_escape(text: str) -> str:
    return clip(text, 140).replace("[", "(").replace("]", ")")


def link(from_dir: Path, target: Path) -> str:
    return Path(os.path.relpath(str(target), str(from_dir))).as_posix()


def page(title: str, lines: List[str]) -> str:
    return "---\ngenerated: true\n---\n\n# %s\n\n%s\n\n%s\n" % (title, GEN_NOTE, "\n".join(lines) if lines else "(none yet)")


def listing(brain: Path, out_dir: Path, items: List[Item], page_key: str, title: str
            ) -> Tuple[List[str], Dict[Path, str]]:
    """Inline lines when <= PAGE_SIZE items, else links to brain/index/<page_key>-NN.md pages."""
    if len(items) <= PAGE_SIZE:
        return [i.render(out_dir) for i in items], {}
    pages: Dict[Path, str] = {}
    lines: List[str] = []
    idx = brain / "index"
    for n in range(0, len(items), PAGE_SIZE):
        chunk = items[n:n + PAGE_SIZE]
        p = idx / ("%s-%02d.md" % (page_key, n // PAGE_SIZE + 1))
        pages[p] = page("%s (page %d)" % (title, n // PAGE_SIZE + 1), [i.render(idx) for i in chunk])
        lines.append("- [%s, page %d](%s) (%d entries, from %s)" % (
            md_escape(title), n // PAGE_SIZE + 1, link(out_dir, p), len(chunk), md_escape(chunk[0].text)))
    return lines, pages


def fill(text: str, block: str, content: str, heading: str = "") -> str:
    """Replace the content between a block's markers; append the block if absent."""
    start, end = "<!-- tess:gen:%s:start -->" % block, "<!-- tess:gen:%s:end -->" % block
    rx = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    new = "%s\n%s\n%s" % (start, content.rstrip("\n"), end)
    if rx.search(text):
        return rx.sub(lambda _m: new, text, count=1)
    tail = "" if text.endswith("\n") or not text else "\n"
    return text + tail + ("\n%s\n\n" % heading if heading else "\n") + new + "\n"


def strip_blocks(text: str) -> str:
    """Hand-written text only (generated blocks removed) - for cap diagnostics."""
    return re.sub(r"<!-- tess:gen:([a-z-]+):start -->.*?<!-- tess:gen:\1:end -->", "", text, flags=re.S)


def links_in(text: str) -> List[str]:
    return re.findall(r"\]\(([^)\s#]+)(?:#[^)\s]*)?\)", text)
