"""Spec -> scaffold DIRECTION and pre-codegen artifact writer.

Deliverable (3): "Establish the spec->code DIRECTION: a stub/interface for
'generate scaffold FROM the spec' — the spec is authoritative." This
module still only PLANS and writes the spec's own artifacts — the real
code generator that consumes a `ScaffoldPlan` and produces runnable files
now lives in the sibling `codegen.py` module (spec_engine.codegen.generate_app()),
continuing this stub into the codegen slice of Phase 2 Epic E4 ("scaffolds
the repo from SPEC.md"). Nothing in THIS module writes application code —
that split stays deliberate so `plan_scaffold_from_spec()` keeps its
"pure, no filesystem access" guarantee no matter how far codegen.py grows.

Two functions:

  - `plan_scaffold_from_spec()` — deterministically enumerates candidate
    scaffold modules FROM a spec's own content (one per data-model entity,
    one per key screen, one per key flow, one per integration, plus a
    single test-suite module derived from acceptance criteria). This is a
    PLAN, not code — `ScaffoldPlan.codegen_status` is always
    `"not_started"` here (see types.py; `codegen.generate_app()` is what
    turns it into `"generated"`). No file is generated by this function;
    it is pure.

  - `write_scaffold_stub()` — writes the artifacts a real codegen step
    needs to consume: the rendered `SPEC.md`, the machine `spec.json`,
    and `.spec-engine/scaffold-plan.json`, PLUS the spec-is-authoritative
    rule written into the generated repo's own `CLAUDE.md`/`AGENTS.md`
    (deliverable (4): "the rule 'code is generated from spec' written
    into the generated repo's own CLAUDE.md/AGENTS.md"). `codegen.generate_app()`
    calls this function itself (passing the FINAL, `"generated"`-status
    plan) rather than duplicating it — this remains the one place those
    four artifacts get written.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Union

from .content import new_id, utc_now_iso
from .render import render_markdown
from .types import ScaffoldModule, ScaffoldPlan, SpecDocument

PathLike = Union[str, Path]

SPEC_DIRECTIVE_MARKER = "<!-- spec-engine: spec-is-authoritative directive -->"

SPEC_DIRECTIVE_BLOCK = f"""{SPEC_DIRECTIVE_MARKER}
# Spec-Authoritative Build Rule

`SPEC.md` in this repository's root is the single source of truth for
what this app does, how it looks, and how it works.

- **CODE IS GENERATED FROM `SPEC.md` — never the reverse.** Do not treat
  generated code as the source of truth.
- Any behavior change starts with a `SPEC.md` edit, not a direct code
  edit. (A code-first edit without a matching spec update is drift — flag
  it, don't silently let it stand.)
- Unresolved items live in `SPEC.md`'s "Open Questions Ledger" — treat
  them as inputs to resolve while building, not blockers that stop work.
- `.spec-engine/scaffold-plan.json` is the current spec->code scaffold
  plan. `codegen_status: "not_started"` means no code has been generated
  yet for this plan; `codegen_status: "generated"` means
  `spec_engine.codegen.generate_app()` has run and real files exist —
  check `.spec-engine/codegen-manifest.json` for exactly which files are
  fully generated vs. labeled stubs (never assume "generated" means
  every module is production-ready; read the manifest).

Source: twiss-io/tess-os spec-engine (TESS-VISION-AND-BUILD-SPEC.html
Phase 1 Epic E2; codegen continues into Phase 2 Epic E4).
"""


def plan_scaffold_from_spec(spec: SpecDocument, *, target_stack: str = "unspecified") -> ScaffoldPlan:
    """Deterministically derive a `ScaffoldPlan` from `spec`. Pure — no
    filesystem access, no randomness. Every module traces back to a named
    `source_section` so the direction "spec is authoritative" is provable,
    not just asserted: nothing in the returned plan has no basis in the
    spec it came from."""
    modules = []

    for i, entity in enumerate(spec.data_model.entities):
        modules.append(
            ScaffoldModule(
                module_id=new_id("mod-backend"),
                source_section=f"data_model.entities[{i}] ({entity.name})",
                kind="backend-model",
                description=f"Persistence model for '{entity.name}'.",
            )
        )

    for i, screen in enumerate(spec.how_it_looks.key_screens):
        modules.append(
            ScaffoldModule(
                module_id=new_id("mod-frontend"),
                source_section=f"how_it_looks.key_screens[{i}] ({screen.name})",
                kind="frontend-page",
                description=screen.description or f"Screen: {screen.name}",
            )
        )

    for i, flow in enumerate(spec.how_it_works.key_flows):
        modules.append(
            ScaffoldModule(
                module_id=new_id("mod-service"),
                source_section=f"how_it_works.key_flows[{i}] ({flow.name})",
                kind="service",
                description=f"Service implementing the '{flow.name}' flow.",
            )
        )

    for i, integration in enumerate(spec.how_it_works.integrations):
        modules.append(
            ScaffoldModule(
                module_id=new_id("mod-integration"),
                source_section=f"how_it_works.integrations[{i}]",
                kind="integration",
                description=f"Integration: {integration}",
            )
        )

    if spec.acceptance_criteria:
        modules.append(
            ScaffoldModule(
                module_id=new_id("mod-tests"),
                source_section="acceptance_criteria",
                kind="test-suite",
                description="Test suite generated from the spec's acceptance criteria.",
                depends_on=[m.module_id for m in modules],
            )
        )

    notes = (
        f"{len(modules)} module(s) derived from spec {spec.spec_id!r} v{spec.spec_version}. "
        f"{len(spec.open_questions)} open question(s) still ride along in SPEC.md and are not "
        "resolved by this scaffold plan — resolve or explicitly defer each one while building."
    )

    return ScaffoldPlan(
        spec_id=spec.spec_id,
        spec_version=spec.spec_version,
        generated_at=utc_now_iso(),
        modules=modules,
        target_stack=target_stack,
        notes=notes,
    )


def write_scaffold_stub(
    spec: SpecDocument,
    target_dir: PathLike,
    *,
    scaffold_plan: ScaffoldPlan = None,
) -> Dict[str, Path]:
    """Write `SPEC.md`, `spec.json`, `.spec-engine/scaffold-plan.json`, and
    a spec-directive block into `target_dir` (a generated app's repo
    root). Returns a dict of the paths written. If `scaffold_plan` is not
    given, one is derived via `plan_scaffold_from_spec(spec)`.

    The directive is appended to `CLAUDE.md` if that file already exists
    and does not already carry the marker (idempotent — running this
    twice never duplicates the block); otherwise both `CLAUDE.md` and
    `AGENTS.md` are created fresh with the directive as their entire
    content, per deliverable (4)'s "written into the generated repo's own
    CLAUDE.md/AGENTS.md" (both harness idioms, not just one)."""
    root = Path(target_dir)
    root.mkdir(parents=True, exist_ok=True)

    written: Dict[str, Path] = {}

    spec_md_path = root / "SPEC.md"
    spec_md_path.write_text(render_markdown(spec), encoding="utf-8")
    written["SPEC.md"] = spec_md_path

    spec_json_path = root / "spec.json"
    spec_json_path.write_text(json.dumps(spec.to_log_record(), indent=2, sort_keys=True), encoding="utf-8")
    written["spec.json"] = spec_json_path

    plan = scaffold_plan or plan_scaffold_from_spec(spec)
    scaffold_dir = root / ".spec-engine"
    scaffold_dir.mkdir(parents=True, exist_ok=True)
    scaffold_plan_path = scaffold_dir / "scaffold-plan.json"
    scaffold_plan_path.write_text(json.dumps(plan.to_log_record(), indent=2, sort_keys=True), encoding="utf-8")
    written[".spec-engine/scaffold-plan.json"] = scaffold_plan_path

    for directive_filename in ("CLAUDE.md", "AGENTS.md"):
        directive_path = root / directive_filename
        if directive_path.is_file():
            existing = directive_path.read_text(encoding="utf-8")
            if SPEC_DIRECTIVE_MARKER not in existing:
                directive_path.write_text(existing.rstrip() + "\n\n" + SPEC_DIRECTIVE_BLOCK, encoding="utf-8")
        else:
            directive_path.write_text(SPEC_DIRECTIVE_BLOCK, encoding="utf-8")
        written[directive_filename] = directive_path

    return written
