// scaffold.js — fetch the Tess OS template and lay it into the target.
//
// DEFAULT source (P0 G-01 BUNDLE fix, 2026-07-21): BUNDLED_TEMPLATE_DIR — a
// LOCAL copy of the template shipped INSIDE the create-tess npm package
// itself (create-tess/template/, generated by scripts/build-template.mjs).
// The default `npm create tess` flow scaffolds from this bundled copy: a
// plain recursive file copy, never a `git clone`, never a network call.
//
// Why this replaced a git-clone default: the OLD default cloned
// DEFAULT_TEMPLATE_SOURCE (the public repo URL, below) pinned to
// DEFAULT_TEMPLATE_REF — a tag in create-tess's OWN `create-tess-v*`
// namespace that, it turns out, was never actually cut across THREE release
// cycles (0.1.1, 0.1.2, 0.1.3 all shipped referencing a tag that doesn't
// exist on origin). Every zero-flag `npm create tess` run hit
// `fatal: Remote branch create-tess-vX.Y.Z not found` — the DEFAULT flow,
// the one every brand-new user takes, was 100% broken. See PR #152 (the
// prior, now-superseded attempt at fixing just the version/tag lockstep —
// it would have kept the *mechanism* that produced this failure, only
// pointed it at a *different* not-yet-cut tag) and the issue it closed for
// the full incident writeup.
//
// `--template-source <git-url>` / `TESS_TEMPLATE_SOURCE` remain fully
// supported as an EXPLICIT, opt-in escape hatch for anyone who deliberately
// wants a live git fetch (their own fork, a mirror, a pinned upstream
// commit) instead of the bundled copy — see fetchTemplate() below; that path
// is unchanged. create-tess/ and .git are always excluded from what gets
// scaffolded, on both paths.
import { existsSync, cpSync, readdirSync, chmodSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { isExcludedRel, makeCopyFilter } from './ignore.js';
import { resetPolicyFile } from './policy-reset.js';
import {
  isLocalSource,
  buildCloneArgs,
  assertSafeTemplateSource,
} from './git-template-source.js';

// The "git opt-in" cluster (DEFAULT_TEMPLATE_SOURCE, DEFAULT_TEMPLATE_REF,
// resolveTemplateRef, buildCloneArgs, isSafeTemplateSource,
// assertSafeTemplateSource) lives in ./git-template-source.js (Reid LOW,
// PR #160 gap-loop fix — this file crossed the 300-line gate; that cluster
// was the self-contained piece). Re-exported here, unchanged, so every
// existing importer (index.js, test/units.test.js) keeps working against
// `./scaffold.js` with zero import-path churn.
export {
  DEFAULT_TEMPLATE_SOURCE,
  DEFAULT_TEMPLATE_REF,
  resolveTemplateRef,
  buildCloneArgs,
  isLocalSource,
  isSafeTemplateSource,
  assertSafeTemplateSource,
} from './git-template-source.js';

// The bundled template's on-disk location — resolved relative to THIS
// file's own location (not process.cwd()), so it resolves correctly whether
// running from the git working tree (`node bin/create-tess.mjs`, dev/CI) or
// from an installed `node_modules/create-tess/` copy (a real `npm create
// tess` run): in both cases `template/` sits one level up from `src/`.
// Generated by `npm run build-template` (create-tess/scripts/build-
// template.mjs) and regenerated automatically by the `prepack` lifecycle
// hook before every `npm pack`/`npm publish` — see package.json — so a
// forgotten manual rebuild can never ship a stale bundle. Committed to the
// repo like any other source file (reviewable in a PR diff); this is what
// package.json's `files` list ships inside the published npm tarball.
export const BUNDLED_TEMPLATE_DIR = fileURLToPath(new URL('../template', import.meta.url));

// The two on-disk copies of the ship-gate policy every scaffold produces:
// the LIVE path an operator actually edits, and its `.tess/core` mirror (the
// pristine copy base_sha-pinned in tess.lock, and what `tessctl restore`
// would reconstruct the live file FROM). Both must be reset identically —
// resetting only the live copy would leave the maintainer's key sitting in
// the core mirror, ready to leak back in on the next `tessctl restore`/
// `tessctl reset`.
const POLICY_REL_PATHS = ['core/policy/policy.yaml', join('.tess', 'core', 'policy', 'policy.yaml')];

// Top-level entries never copied into a scaffolded instance. Derived from the
// single shared ignore source (create-tess/src/ignore.js) — NOT a parallel list.
// This is only the fast top-level skip; per-file exclusion (globs, multi-component
// secret paths, snapshot/staging content) is enforced by makeCopyFilter during
// the recursive cpSync so a local --template-source can never drag in the
// author's vault.age / vault.recipients / snapshots / .env* / keys (Quinn MEDIUM).
function isExcludedTopEntry(entry) {
  return isExcludedRel(entry);
}

export function ensurePython3() {
  try {
    execFileSync('python3', ['--version'], { stdio: 'ignore' });
  } catch {
    throw new Error(
      'python3 is required (the Tess OS keystone, tessctl, is Python). Install Python 3 and retry.',
    );
  }
}

// Clobber-protection (design doc §5.1). Returns a reason string if the target
// must be refused, or null if it's safe to proceed.
export function clobberReason(targetDir, force) {
  if (force) return null;
  if (existsSync(join(targetDir, 'operator', 'profile.json')) ||
      existsSync(join(targetDir, 'tess.lock'))) {
    return (
      'This directory is already a Tess OS install. To change your setup, run ' +
      '`tessctl reconfigure` (or edit operator/profile.json and re-render). ' +
      'To start fresh elsewhere, pass a new directory or --force.'
    );
  }
  if (existsSync(targetDir)) {
    const entries = readdirSync(targetDir).filter((e) => e !== '.DS_Store');
    if (entries.length > 0) {
      return `Target directory ${targetDir} is not empty. Pass --force to scaffold into it anyway.`;
    }
  }
  return null;
}

// Stage the template into `stagingDir` (a temp dir) so the journey can read the
// roster and validate names before the target is touched (atomicity, §6.5).
//
// `ref` (optional) pins a git-URL clone to a specific tag/branch/SHA —
// resolved by the caller via resolveTemplateRef() so this function stays a
// pure "fetch whatever I was told to fetch" primitive. Ignored entirely for
// a local source (there is no ref to pin — a local directory is copied as-is).
export function fetchTemplate(source, stagingDir, ref = null) {
  // Defence in depth — refuse a flag-shaped source before it can reach git.
  assertSafeTemplateSource(source);
  mkdirSync(stagingDir, { recursive: true });
  if (isLocalSource(source)) {
    const abs = resolve(source);
    const filter = makeCopyFilter(abs);
    for (const entry of readdirSync(abs)) {
      if (isExcludedTopEntry(entry)) continue;
      cpSync(join(abs, entry), join(stagingDir, entry), {
        recursive: true,
        filter,
        dereference: false,
      });
    }
    return { mode: 'local', source: abs };
  }
  // Git URL → shallow clone (pinned to `ref` when set), then strip .git +
  // create-tess. The `--` end-of-options guard means a flag-shaped <source>
  // can never be read as a git option (HIGH-2a; belt-and-suspenders with
  // assertSafeTemplateSource).
  try {
    execFileSync('git', buildCloneArgs(source, stagingDir, ref), { stdio: 'inherit' });
  } catch (err) {
    if (ref) {
      throw new Error(
        `git clone --branch ${ref} ${source} failed — the pinned ref "${ref}" may not ` +
          `exist yet at this source (has it been released?). Override with ` +
          `--template-ref/TESS_TEMPLATE_REF to target a different ref. ${err.message}`,
      );
    }
    throw err;
  }
  // Strip excluded dirs a clone brings in (so they never reach the target).
  for (const ex of ['.git', 'create-tess']) {
    const p = join(stagingDir, ex);
    if (existsSync(p)) rmSync(p, { recursive: true, force: true });
  }
  return { mode: 'git', source, ref };
}

// Promote the staged template into the (confirmed) target directory.
//
// Returns { policyReset } — see resetScaffoldedPolicyKeys below. The caller
// (index.js) uses `policyReset.changed` to decide whether the scaffolded
// tess.lock also needs a scoped re-pin (a normalization that intentionally
// alters `.tess/core/policy/policy.yaml`'s bytes invalidates the base_sha
// tess.lock already pinned for that entry — `tessctl doctor` would otherwise
// report CORE TAMPER on a project that was never tampered with, only scaffolded).
export function promote(stagingDir, targetDir) {
  mkdirSync(targetDir, { recursive: true });
  const filter = makeCopyFilter(stagingDir);
  for (const entry of readdirSync(stagingDir)) {
    if (isExcludedTopEntry(entry)) continue;
    cpSync(join(stagingDir, entry), join(targetDir, entry), {
      recursive: true,
      filter,
      dereference: false,
    });
  }
  // Ensure the keystone wrappers are executable post-copy.
  for (const w of ['tessctl', join('.tess', 'bin', 'tessctl')]) {
    const p = join(targetDir, w);
    if (existsSync(p)) {
      try { chmodSync(p, 0o755); } catch { /* best effort */ }
    }
  }
  const policyReset = resetScaffoldedPolicyKeys(targetDir);
  return { policyReset };
}

// Fail-closed scaffold reset: a scaffolded project must never inherit the
// SOURCE repo's registered verifier_keys/signoff_keys (its OWN trust anchor —
// see the header comment in policy-reset.js). Applies the same
// comment-preserving reset to BOTH the live policy and its `.tess/core`
// mirror, independently (each is skipped, not required, if it doesn't exist —
// a minimal/test template may ship neither). NOT done via ignore.js exclusion
// — the scaffold still needs every other rule/comment in the file; only the
// two ALLOWED-KEY-SET maps are reset.
//
// Returns { changed, files } — `files` lists which of POLICY_REL_PATHS were
// actually rewritten (empty if the source already shipped the clean, empty
// default — the common case today, before any real verifier is registered).
export function resetScaffoldedPolicyKeys(targetDir) {
  const files = [];
  for (const rel of POLICY_REL_PATHS) {
    const { changed } = resetPolicyFile(join(targetDir, rel));
    if (changed) files.push(rel);
  }
  return { changed: files.length > 0, files };
}

// M2 — framework-managed paths that a `--force` re-scaffold over an EXISTING
// install must clean-replace rather than merge into. Without this, cpSync layers
// the new template over the old one and stale managed files (a renamed agent, a
// removed doctrine file) survive. Operator space (operator/**) and any other user
// data are deliberately NOT listed — they are preserved across a forced re-run.
export const MANAGED_PATHS = [
  join('.claude', 'agents'),
  join('.claude', 'commands'),
  'conductor',
  join('.tess', 'core'),
  'CLAUDE.md',
];

// Clear the managed dirs/files in `targetDir` so the subsequent promote() lays
// down a clean copy. Best-effort + idempotent (missing paths are skipped).
export function clearManagedDirs(targetDir) {
  for (const rel of MANAGED_PATHS) {
    const p = join(targetDir, rel);
    if (existsSync(p)) {
      try { rmSync(p, { recursive: true, force: true }); } catch { /* best effort */ }
    }
  }
}
